# GlobalMarket 配置文件

# 最大上架物品数量 (-1 为无限制)
max-listings-per-player: -1

# 是否启用经济系统支持 (需要Vault插件)
use-economy: true

# 交易税百分比 (0-100)
transaction-tax: 1.0
# 上架费用百分比 (物品价格的百分比，0为免费)
listing-fee-percentage: 0.5
# 上架费用计算方式: round (四舍五入) 或 floor (去尾法/向下取整)
listing-fee-calculation-method: floor

# 反物品复制设置
anti-duplication:
  # 启用反复制机制
  enabled: true
  # 上架超时时间（毫秒），超过此时间未完成上架则自动取消
  timeout-milliseconds: 5000
  # 是否启用玩家在线状态检查
  online-check: true
  # 是否启用物品存在性验证
  item-validation: true
  # 失败时是否发送详细错误消息
  detailed-errors: true
  # 是否启用离线交易管理器
  use-offline-transaction-manager: true
  # 最大重试次数
  max-retries: 3
  # 重试间隔（毫秒）
  retry-delay: 1000

# 物品过期时间 (小时，0为不过期)
listing-expire-time: 4320

# 数据存储类型: yaml, mysql
storage-type: yaml

# 数据库配置 (仅当 storage-type 为 mysql 时生效)
database:
  # MySQL配置示例
  mysql:
    host: localhost
    port: 3306
    database: globalmarket
    username: minecraft
    password: password
    ssl: false
    # 连接池配置
    pool-size: 10
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000

# 是否记录交易日志
log-transactions: true

# GUI设置
gui:
  # 每页显示物品数量
  items-per-page: 45
  # 是否启用动画效果
  enable-animation: true
  # 自动刷新间隔 (秒，0为不自动刷新)
  auto-refresh: 30

# 邮箱设置
mailbox:
  # 每页显示物品数量
  items-per-page: 45
  # 交易记录书名
  transaction-record-title: "交易记录"
  # 交易记录作者
  transaction-record-author: "GlobalMarket"

# 消息配置
messages:
  prefix: "&8[&6GlobalMarket&8] &r"
  no-permission: "&c你没有权限执行此操作!"
  item-sold: "&a你的物品已成功出售!"
  item-purchased: "&a你已成功购买物品!"

  invalid-price: "&c请输入有效的价格!"
  not-enough-money: "&c你没有足够的金币!"
  insufficient-funds: "&c余额不足! 需要: %amount%"
  purchase-success: "&a购买成功! 花费: %amount%"
  create-success: "&a物品上架成功! 总价: %total% (%amount% x %count% 个)"
  listing-fee-charged: "&a已收取上架费用: %fee% (物品价格的 %percentage%%)"
  item-received: "&a物品已存入邮箱!"
  money-received: "&a资金已到账: %amount%"
  inventory-full: "&c背包已满! 请先清理背包空间。"
  transaction-record-received: "&a收到交易记录: %item% x%amount% 售价: %price% 税款: %tax% 实际收入: %net%"
  
  # 新添加的消息通知配置
  # 交易通知消息
  purchase-notification-buyer: "&a[成功] 你购买了 %amount% 个 %item% &a总价: %price% &7物品已存入邮箱!"
  purchase-notification-seller: "&6[交易] %buyer% 购买了你上架的 %amount% 个 %item% &6售价: %price% &a实际收入: %net% &7物品已存入邮箱!"
  
  # 邮箱到达通知
  mailbox-notification-new-item: "&b[邮箱] 有新的物品到达邮箱! &7使用 /market mail 查看详情"
  mailbox-notification-removed: "&e[下架] 你的物品已从市场下架并返回邮箱! &7使用 /market mail 查看详情"
  mailbox-notification-sent: "&d[邮寄] %sender% 给你邮寄了物品! &7使用 /market mail 查看详情"
  
  # 玩家上线邮箱提示
  mailbox-login-summary: "&b[邮箱] 您有新的邮件！"
  mailbox-login-detail: "&7  - %count% 个 %type%"
  mailbox-login-command: "&7使用 /market mail 查看邮箱详情"