name: GlobalMarket
version: 1.0.0
main: com.globalmarket.GlobalMarket
api-version: '1.21'
description: A global market plugin for Minecraft servers
author: GlobalMarket Team
website: https://github.com/globalmarket/globalmarket

commands:
  market:
    description: Global market command
    usage: /market <create|listing|remove|gui|mailbox|reload>
    aliases: [market]

permissions:
  globalmarket.use:
    description: Allow players to use market commands
    default: true
  globalmarket.reload:
    description: Allow reloading the plugin
    default: op
  globalmarket.sell:
    description: Allow selling items
    default: true
  globalmarket.buy:
    description: Allow buying items
    default: true
  globalmarket.gui:
    description: Allow using GUI interface
    default: true